terraform/ansible-playbook.yml
terraform/roles/k9s/LICENSE
terraform/roles/k9s/README.md
terraform/roles/k9s/defaults/Windows.yml
terraform/roles/k9s/defaults/main.yml
terraform/roles/k9s/meta/main.yml
terraform/roles/k9s/tasks/main.yml
terraform/roles/k9s/vars/Windows.yml
terraform/roles/k9s/vars/main.yml

Added k9s role from [here](https://github.com/aries1980/ansible-k9s) plus emacs

add k9s and emacs to workshop VM

---

gloo/gloo/README.md
terraform/ansible-playbook.yml

Some changes in this PR:
- Add Chrome to environment path
- More command results shown
- Editorial changes

Changes from Gloo workshop review

---

gloo/gloo/README.md

Cleaned up a "NOTE" markup mistake from my previous commit, plus some more minor editorial tweaks.

more gloo workshop content cleanup

---

gloo-mesh/README.md

as I run through the workshop today

A few misc update

---

gloo-portal/README.md

Fixing some small things I noticed while delivering the SoloCon Portal workshop.

post-solocon portal workshop tweaks

---

gloo-mesh/README.md

Istio 1.9 no longer supports it.  I tried to install it with it enabled, the pod is not installed either.

remove coredns

---

SUMMARY.md

Make Portal header format match the other workshops.

One final SUMMARY.md tweak

---

gloo-edge/gloo-edge/README.md

Addresses issue #28 by pinning Keycloak to known version supporting expected metadata.

Pin keycloak version

---

gloo-portal/README.md

Highlighted where yaml config changed in portal workshop and fixed typos.

Highlight yaml config changes in portal workshop guide

---

istio-day2/1-deploy-istio/01-run-envoy.md
istio-day2/1-deploy-istio/02-install-istio.md
istio-day2/1-deploy-istio/03-observability.md
istio-day2/1-deploy-istio/04-ingress-gateway.md
istio-day2/1-deploy-istio/06-mtls-rollout.md
istio-day2/1-deploy-istio/07-controlling-config.md

Made some small editorial changes to Deploy Istio workshop guide.

Editorial changes for Deploy Istio workshop guide

---

istio-day2/1-deploy-istio/04-ingress-gateway.md
istio-day2/1-deploy-istio/05a-bonus.md
istio-day2/1-deploy-istio/06-mtls-rollout.md
istio-day2/1-deploy-istio/07-controlling-config.md
istio-day2/1-deploy-istio/labs/04/ingress-gw-access-logging.yaml
istio-day2/1-deploy-istio/labs/04/my-user-gw-https.yaml
istio-day2/1-deploy-istio/labs/04/my-user-gw-vs.yaml
istio-day2/1-deploy-istio/labs/04/web-api-gw-https.yaml
istio-day2/1-deploy-istio/labs/05/web-api-access-logging.yaml
istio-day2/1-deploy-istio/labs/05/web-api-dr.yaml
istio-day2/1-deploy-istio/labs/05/web-api-gw-vs-subset.yaml
istio-day2/1-deploy-istio/labs/06/web-api-access-logging-audit.yaml
istio-day2/1-deploy-istio/labs/06/web-api-access-logging.yaml
istio-day2/1-deploy-istio/labs/07/cleanup.sh
istio-day2/1-deploy-istio/labs/07/helloworld-vs-delegate.yaml
istio-day2/1-deploy-istio/labs/07/helloworld-vs.yaml
istio-day2/1-deploy-istio/labs/07/vs-delegate.yaml
istio-day2/1-deploy-istio/labs/07/web-api-gw-https-istiosystem.yaml
istio-day2/1-deploy-istio/labs/07/web-api-gw-vs-delegate.yaml
istio-day2/1-deploy-istio/labs/07/web-api-gw-vs-exportto.yaml
istio-day2/1-deploy-istio/labs/07/web-api-gw-vs.yaml
istio-day2/1-deploy-istio/labs/08/web-api-gw-vs.yaml
istio-day2/1-deploy-istio/labs/cleanup.sh
istio-day2/1-deploy-istio/sample-apps/ingress/web-api-gw-vs.yaml
istio-day2/1-deploy-istio/sample-apps/ingress/web-api-gw.yaml

- apiversion unified to v1beta1
- cleanup script simplified
- removed empty route from delegation vs (lab07)

minor improvements

---

INSTRUCTOR.md
terraform/ansible-playbook.yml
terraform/ansible.cfg

+ Playbook can be safely run multiple times
+ Disabled that annoying 'keyring' popup
+ Disable 'unsafe copy' popup
+ Terminals show _solo.io workshops_ in the title
+ Optional parameters _reboot_vm_ and _reset_repo_
+ Licenses are now hidden in the log
+ Alternative way of cleaning known_hosts after terraform creation (instructor.md)
+ Other minor optimizations

Idempotent playbook + some optimizations

---

istio-day2/1-deploy-istio/06-mtls-rollout.md
istio-day2/1-deploy-istio/labs/06/web-api-access-logging-audit.yaml

+ Added answer to mystery question in Lab6
+ Envoy logs enriched to see (even) with more clarity how mTLS use SPIFFE identities

lab6_mtls_details

---

terraform/gce/vm-image/main.tf
terraform/gce/vm-replica/main.tf

+ allow duplicated names in different namespaces

allow same name in different workspaces

---

gloo-edge/gloo-edge/README.md
gloo-edge/gloo-edge/labs/01/check.sh
gloo-edge/gloo-edge/labs/01/cleanup.sh
gloo-edge/gloo-edge/labs/01/solve.sh
gloo-edge/gloo-edge/labs/02/check.sh
gloo-edge/gloo-edge/labs/02/cleanup.sh
gloo-edge/gloo-edge/labs/02/solve.sh
scripts/extract-lab.sh
scripts/solve.sh

+ You can now solve any lab just calling `labs/01/solve.sh`
+ You can now clean any lab just calling `labs/01/cleanup.sh`
+ You can now check any lab just calling `labs/01/check.sh`

add some testing to the labs

---

INSTRUCTOR.md
TROUBLESHOOTING.md
terraform/ansible-playbook.yml
terraform/ansible.cfg
terraform/roles/repo/defaults/main.yml
terraform/roles/repo/tasks/main.yml

+ Added istio_workshops to the provisioning script (you must have the proper key in your machine)
+ Troubleshooting section in Instructor.md
+ Allow pipelining for faster provisioning

private_repo

---

terraform/aws/eks/main.tf
terraform/aws/eks/templates/eks-admin.yaml

+ added an additional user to ./output/<cluster_name>/kubeconfig-<cluster_name> so it can be used by guests

eks-admin-kubeconfig

---

terraform/ansible-playbook.yml
terraform/aws/eks/main.tf

+ Added MGMT, CLUSTER1, CLUSTER2 
+ AWS: Removing security groups created by loadbalancers created by k8s controller. This was blocking terraform to cleanly destroy all resources

added default env variables

---

gloo-portal/README.md

fixed a few typos and mistakes

fix a few issues

---

gloo-portal/README.md

Small editorial changes from my recent prep for a private Portal workshop.

Portal workshop editorial tweaks

---

packer/instruqt-gloo-edge/Makefile
packer/instruqt-gloo-edge/files/import-docker-images.sh
packer/instruqt-gloo-edge/files/k3s-install.sh
packer/instruqt-gloo-edge/files/k3s-start.sh
packer/instruqt-gloo-edge/files/k3s.service
packer/instruqt-gloo-edge/files/kubectl-proxy.service
packer/instruqt-gloo-edge/files/node-install.sh
packer/instruqt-gloo-edge/files/package.json
packer/instruqt-gloo-edge/files/start.sh
packer/instruqt-gloo-edge/k3s.pkr.hcl
packer/instruqt-gloo-mesh/Makefile
packer/instruqt-gloo-mesh/files/import-docker-images.sh
packer/instruqt-gloo-mesh/files/k3s-install.sh
packer/instruqt-gloo-mesh/files/k3s-start.sh
packer/instruqt-gloo-mesh/files/k3s.service
packer/instruqt-gloo-mesh/files/kubectl-proxy.service
packer/instruqt-gloo-mesh/files/node-install.sh
packer/instruqt-gloo-mesh/files/package.json
packer/instruqt-gloo-mesh/files/start.sh
packer/instruqt-gloo-mesh/files/vcluster-install.sh
packer/instruqt-gloo-mesh/k3s.pkr.hcl
packer/readme.md

instructions in `packer/readme.md`

packer build for instruqt - gloo edge

---

gloo-mesh-2-0-airgap/scripts/deploy-multi.sh
gloo-mesh-2-0-eks-and-openshift/scripts/deploy-multi.sh
gloo-mesh-2-0-eks-single-workspace-no-revisions/scripts/deploy-multi.sh
gloo-mesh-2-0-eks/scripts/deploy-multi.sh
gloo-mesh-2-0-gateway/scripts/deploy-multi.sh
gloo-mesh-2-0-node-ports/scripts/deploy-multi.sh
gloo-mesh-2-0-openshift/scripts/deploy-multi.sh
gloo-mesh-2-0-single-cluster-single-workspace-openshift-nodeport/scripts/deploy-multi.sh
gloo-mesh-2-0-single-cluster-single-workspace-openshift/scripts/deploy-multi.sh
gloo-mesh-2-0-single-cluster-single-workspace/scripts/deploy-multi.sh
gloo-mesh-2-0-single-cluster/scripts/deploy-multi.sh
gloo-mesh-2-0-single-workspace/scripts/deploy-multi.sh
gloo-mesh-2-0/scripts/deploy-multi.sh

[bot] Merge automation
